export const CHANGE_DISPLAY_SUBMENU = 'CHANGE_DISPLAY_SUBMENU'
export const INIT_CATALOG = 'INIT_CATALOG';
export const INIT_CATALOG_SUCCESS = 'INIT_CATALOG_SUCCESS';
export const INIT_CATALOG_FAIL = 'INIT_CATALOG_FAIL';
export const SET_ACTIVE_ID = 'SET_ACTIVE_ID';