export const INIT_MENU = 'INIT_MENU';
export const INIT_MENU_SUCCESS = 'INIT_MENU_SUCCESS';
export const INIT_MENU_FAIL = 'INIT_MENU_FAIL';
export const INIT_SUB_MENU = 'INIT_SUB_MENU';
export const INIT_SUB_MENU_SUCCESS = 'INIT_SUB_MENU_SUCCESS';
export const INIT_SUB_MENU_FAIL = 'INIT_SUB_MENU_FAIL';
export const SET_ID_ACTIVE_MENU = 'SET_ID_ACTIVE_MENU';
export const SET_IS_MENU_ACTIVE = 'SET_IS_MENU_ACTIVE'
export const SHOW_CARD_SUB_MENU = 'SHOW_CARD_SUB_MENU'

export const IS_CATALOG = 'IS_CATALOG'
export const INIT_PRODUCTS = 'INIT_PRODUCTS'
export const INIT_PRODUCTS_SUCCESS = 'INIT_PRODUCTS_SUCCESS'
export const INIT_PRODUCTS_FAIL = 'INIT_PRODUCTS_FAIL'

