export const INIT_MENU = 'INIT_MENU';
export const INIT_MENU_SUCCESS = 'INIT_MENU_SUCCESS';
export const INIT_MENU_FAIL = 'INIT_MENU_FAIL';
export const SET_ID_ACTIVE_MENU = 'SET_ID_ACTIVE_MENU';
export const SET_IS_MENU_ACTIVE = 'SET_IS_MENU_ACTIVE'
export const SHOW_CARD_SUB_MENU = 'SHOW_CARD_SUB_MENU'

export const IS_PRODUCT = 'IS_PRODUCT'
export const INIT_PRODUCTS = 'INIT_PRODUCTS'
export const INIT_PRODUCTS_SUCCESS = 'INIT_PRODUCTS_SUCCESS'
export const INIT_PRODUCTS_FAIL = 'INIT_PRODUCTS_FAIL'

export const INIT_FILTERS = 'INIT_FILTERS'
export const INIT_FILTERS_SUCCESS = 'INIT_FILTERS_SUCCESS'
export const INIT_FILTERS_FAIL = 'INIT_FILTERS_FAIL'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CLEAR_FILTERS_ALL = 'CLEAR_FILTERS_ALL'
export const SHOW_FILTER_FLAG = 'SHOW_FILTER_FLAG'
export const CHANGE_FILTER_MARK = 'CHANGE_FILTER_MARK'
export const INIT_ORDER_GROUP_LIST_SUCCESS = 'INIT_ORDER_GROUP_LIST_SUCCESS'

export const SET_AUTH = 'SET_AUTH'
export const SET_ADMIN = 'SET_ADMIN'
export const AUTH_DIALOG_OPEN = 'AUTH_DIALOG_OPEN'


