export const INIT_MENU = 'INIT_MENU';
export const INIT_MENU_SUCCESS = 'INIT_MENU_SUCCESS';
export const INIT_MENU_FAIL = 'INIT_MENU_FAIL';
export const SET_ID_ACTIVE_MENU = 'SET_ID_ACTIVE_MENU';
export const SET_IS_MENU_ACTIVE = 'SET_IS_MENU_ACTIVE'
export const SHOW_CARD_SUB_MENU = 'SHOW_CARD_SUB_MENU'

export const IS_PRODUCT = 'IS_PRODUCT'
export const INIT_PRODUCTS = 'INIT_PRODUCTS'
export const INIT_PRODUCTS_SUCCESS = 'INIT_PRODUCTS_SUCCESS'
export const INIT_PRODUCTS_FAIL = 'INIT_PRODUCTS_FAIL'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const UPDATE_RATING = 'UPDATE_RATING'
export const INIT_PRODUCTS_SUCCESS_ONE = 'INIT_PRODUCTS_SUCCESS_ONE'
export const INIT_PRODUCTS_ONE = 'INIT_PRODUCTS_ONE'

export const INIT_FILTERS = 'INIT_FILTERS'
export const INIT_FILTERS_SUCCESS = 'INIT_FILTERS_SUCCESS'
export const INIT_FILTERS_FAIL = 'INIT_FILTERS_FAIL'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CLEAR_FILTERS_ALL = 'CLEAR_FILTERS_ALL'
export const SHOW_FILTER_FLAG = 'SHOW_FILTER_FLAG'
export const CHANGE_FILTER_MARK = 'CHANGE_FILTER_MARK'
export const INIT_ORDER_GROUP_LIST_SUCCESS = 'INIT_ORDER_GROUP_LIST_SUCCESS'

export const IS_AUTH = 'IS_AUTH'
export const IS_ADMIN = 'IS_ADMIN'
export const AUTH_DIALOG_OPEN = 'AUTH_DIALOG_OPEN'
export const LOAD_USER = 'LOAD_USER'
export const INIT_USER = 'INIT_USER';
export const INIT_USER_SUCCESS = 'INIT_USER_SUCCESS';
export const INIT_USER_FAIL = 'INIT_USER_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT'


export const SET_CATALOG_TABLE_PARENT = 'SET_CATALOG_TABLE_PARENT'
export const CHANGE_ONE_CATEGORY = 'CHANGE_ONE_CATEGORY'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const INIT_REFERENCES = 'INIT_REFERENCES'
export const INIT_REFERENCES_FAIL = 'INIT_REFERENCES_FAIL'
export const INIT_REFERENCES_SUCCESS = 'INIT_REFERENCES_SUCCESS'
export const UPDATE_REFERENCE = 'UPDATE_REFERENCE'
export const CREATE_REFERENCE = 'CREATE_REFERENCE'
export const DELETE_REFERENCE = 'DELETE_REFERENCE'

export const INIT_TOP_PRODUCTS= 'INIT_TOP_PRODUCTS'
export const INIT_TOP_PRODUCTS_SUCCESS = 'INIT_TOP_PRODUCTS_SUCCESS'
export const INIT_TOP_PRODUCTS_FAIL = 'INIT_TOP_PRODUCTS_FAIL'
